#!/usr/bin/env bash
set -E -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"

UPSTREAM_PACKAGE_NAME="cAdvisor/Go"
UPSTREAM_CADVISOR_VERSION_CONFIG_KEY="CADVISOR_VERSION"
UPSTREAM_CADVISOR_GIT_REPO="https://github.com/google/cadvisor"
UPSTREAM_GO_IMAGE_NAME_CONFIG_KEY="GO_IMAGE_NAME"
UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY="GO_IMAGE_TAG"
UPSTREAM_GO_IMAGE_PATTERN="^[0-9]+\.[0-9]+\.[0-9]+-go-.+$"

RELEASE_PACKAGE_NAME="cAdvisor"
RELEASE_PACKAGE_VERSION_CONFIG_KEY="CADVISOR_VERSION"
RELEASE_TAG_PACKAGE_NAME="cadvisor"

TEST_TYPE="background"
TEST_CONTAINER_TYPE="cadvisor"
TEST_CONTAINER_START_WAIT_SECONDS="10"

current_cadvisor_version() {
    get_config_arg ${UPSTREAM_CADVISOR_VERSION_CONFIG_KEY:?}
}

current_go_image_version() {
    get_config_arg ${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY:?}
}

current_upstream_version() {
    local cadvisor_ver="$(current_cadvisor_version)"
    local go_image_ver="$(current_go_image_version)"
    echo "${cadvisor_ver:?}/${go_image_ver:?}"
}

latest_cadvisor_version() {
    git_remote_repo_latest_tag "${UPSTREAM_CADVISOR_GIT_REPO:?}"
}

latest_go_image_version() {
    dockerhub_latest_tag \
        "$(get_config_arg ${UPSTREAM_GO_IMAGE_NAME_CONFIG_KEY:?})" \
        "${UPSTREAM_GO_IMAGE_PATTERN:?}"
}

latest_upstream_version() {
    local cadvisor_ver="$(latest_cadvisor_version)"
    local go_image_ver="$(latest_go_image_version)"
    echo "${cadvisor_ver:?}/${go_image_ver:?}"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    local cur_cadvisor_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 1)"
    local cur_go_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 2)"
    local latest_cadvisor_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 1)"
    local latest_go_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 2)"
    echo "Updating ${UPSTREAM_PACKAGE_NAME:?} ${UPSTREAM_CADVISOR_VERSION_CONFIG_KEY:?}/${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_CADVISOR_VERSION_CONFIG_KEY:?}" "${latest_cadvisor_ver:?}"
    set_config_arg "${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY:?}" "${latest_go_ver:?}"
    git add ${ARGS_FILE:?}
}

package_current_release_version() {
    get_config_arg "${RELEASE_PACKAGE_VERSION_CONFIG_KEY:?}"
}

test_start_container() {
    local container_name="${1:?}"

    docker run \
        --user root \
        --cap-add SYSLOG \
        --name ${container_name:?} \
        --detach \
        --rm \
        --volume /var/run:/var/run:ro \
        --publish 127.0.0.1:8082:8080 \
        ${IMAGE:?}
}

test_image_after_container_startup() {
    local container_name="${1:?}"
    test_http_endpoint "${container_name:?}" http 127.0.0.1 8082
}
